name: SynTools CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "3.27.0"
          ninjaVersion: "latest"

      - name: Configure SynTools
        run: cmake -S . -B build-tools -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build syntools only
        run: cmake --build build-tools --target syntools --parallel